### ISSUE TITLE
Driver update

### ISSUE THREAD

**Issue by grantmk** [coolstar/sklhdaudbus#5]
Hi, I'm trying to update to latest driver for Intel SOF audio - please can you help? Portal has zero purchased license links and I'm stuck on 1.0.2 which crashes on almost every sleep. Thanks.

**Comment by coolstar** [comment]
Log into the portal at https://coolstar.org/chromebook/driverlicense/ and download the latest driver from your existing account

**Comment by grantmk** [comment]
Thanks, I've been through that but there is no link in there. I changed the SSD so need to reset the license as well. I cannot message on Patreon without a current subscription so hence why I'm coming over here. If you could so that it would be much appreciated. My registered SOF Intel audio driver email is (without dashes) g-r-a-n-t-m-k@gmail.com :

**Comment by sonvirgo** [comment]
> Hi, I'm trying to update to latest driver for Intel SOF audio - please can you help? Portal has zero purchased license links and I'm stuck on 1.0.2 which crashes on almost every sleep. Thanks.

I have locally built release here, very welcome if you donate
![Screenshot (9)](https://github.com/user-attachments/assets/b1b98557-1ca7-4e57-9658-e08191159fd2)

**Comment by grantmk** [comment]
Where exactly?

**Comment by sonvirgo** [comment]
> Where exactly?
I can receive money within French and Australia like Wise or Postal.
